<a href="https://colab.research.google.com/github/Lizylun/MaterialTHC/blob/main/Clase9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::3])

[1 4 7]


In [7]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 1:4])

[2 3 4]


In [8]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, :])

[1 2 3 4 5]


In [14]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:5, 3])

[4 9]


In [15]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:1, 2:5])

[[3 4 5]]


In [16]:
#Ejercicio en clase

x=np.array([1,2,3])
y=np.array([4,5,6])

print(x+y)


[5 7 9]


In [19]:
x=np.array([1,2,3])
y=np.array([4,5,6])

producto=x*y
print(f"el producto es {producto}")

el producto es [ 4 10 18]


In [18]:
x=np.array([1,2,3])
y=np.array([4,5,6])

print(x/y)

[0.25 0.4  0.5 ]


In [20]:
angulos=np.array([0,np.pi/2,np.pi])
cos=np.cos(angulos)
print(f"los cosenos {cos}")
print(f"de los angulos {angulos}")

los cosenos [ 1.000000e+00  6.123234e-17 -1.000000e+00]
de los angulos [0.         1.57079633 3.14159265]


In [26]:
numero= input("ingrese un numero del 1 al 10")
np.random.randint(0,10,size=1)
while i<5:


SyntaxError: ignored