<a href="https://colab.research.google.com/github/Lizylun/MaterialTHC/blob/main/Clase8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
matriz = np.array([[1,2,3], [4,5,6],[7,8,9]])
suma = 0
for i in range (len(matriz)):
 for j in range (len(matriz[i])):
  suma +=matriz[i,j]
print (suma)


45


In [19]:
def ProdPunto(a,b):
  PP=0.0
  for i in range(len(a)):
    PP=PP+a[i]*b[i]
  return PP

In [20]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3=np.array([[1,1,1],[1,1,1],[1,1,1]])
Pp_por_reng=np.array([0,0,0])
Pp_por_col=np.array([0,0,0])


In [21]:
for i in range(len(arr2)):
  Pp_por_reng[i]=ProdPunto(arr2[i],arr3[i])
Pp_por_reng

array([ 6, 15, 24])

In [22]:
def AgarraCol(a,col):
  nuevo=[]
  for i in range(len(a)):
    nuevo.append(a[i,col])

  return np.array(nuevo)


In [25]:
col1=AgarraCol(arr2,0)
col1

array([1, 4, 7])

In [27]:
for i in range(len(arr2)):
   Pp_por_col[i]=ProdPunto(AgarraCol(arr2,i),AgarraCol(arr3,i))

Pp_por_col

array([12, 15, 18])